<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.AspNetCore.TestHost" />
		<PackageReference Include="Microsoft.NET.Test.Sdk">
		  <TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Moq">
		  <TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Core.Idempotency.PostgreSql\Core.Idempotency.PostgreSql.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="Scripts\postgresql.sql">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
